In [187]:
import os
import pandas as pd 
import cv2
import numpy as np

from phos_label_generator import gen_label
from phoc_label_generator import gen_phoc_label

In [16]:
dataPath="/home/aniketag/Documents/phd/yolov5/data/datasets/data_444_april.csv"

df=pd.read_csv(dataPath)
df.reset_index(drop=True)

print(df.shape)
print(" no of unique words:",len(df.text.unique()))
df.head(5)

(115187, 13)
 unique: 13550

,image_name,class,width,height,org_x1,org_y1,org_x2,org_y2,text,x,y,w,h
0,g06-031n.png,1,2479,3542,435,678,450,697,',0.18,0.19,0.01,0.01
1,g06-031n.png,1,2479,3542,425,683,663,777,What,0.22,0.21,0.10,0.03
2,g06-031n.png,1,2479,3542,640,726,696,779,a,0.27,0.21,0.02,0.01
3,g06-031n.png,1,2479,3542,727,685,1128,820,frightful,0.37,0.21,0.16,0.04
4,g06-031n.png,1,2479,3542,1129,692,1365,779,event,0.50,0.21,0.10,0.02

In [31]:
"""
    get most frequent words
"""

textFreq=df.text.value_counts()

"""
    most frquent words by observation of frequency
"""
words=["the","of","to","and","was","that","with","which","have","would","their","there","about"]

In [18]:
#textFreq[50:100]

In [23]:
testImgPath="/home/aniketag/Documents/phd/yolov5/data/datasets/forms//" 
cropSavePath="/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyData//"

"""
    BELOW CROPS FOR WORDS ARE CREATED
"""

In [29]:

lastImageName=""

for word in words:
    
    temp=df[df["text"]==word]
    temp=temp[["image_name","org_x1","org_y1","org_x2","org_y2","text"]]
    
    print(" word:",word," temp:",temp.shape)
    
    try:
        os.mkdir(cropSavePath+word)
    
    except Exception as e:
        pass
    
    for indx,row in temp.iterrows():
    
        imgName,x1,y1,x2,y2,text=row
        
        if imgName!=lastImageName:
            
            image=cv2.imread(testImgPath+imgName)
            #print("image=",image.shape)
            
        else:
            continue
        
        """
            crate crops
        """
            
        cropped_image = image[y1-10:y2+20, x1-10:x2+20]
 
        cv2.imwrite(cropSavePath+word+"//"+imgName+"_"+str([x1,y1,x2,y2])+"_"+text+".png",cropped_image)

 word: the  temp: (5825, 6)
 word: of  temp: (3191, 6)
 word: to  temp: (2648, 6)
 word: and  temp: (2474, 6)
 word: was  temp: (1135, 6)
 word: that  temp: (1127, 6)
 word: with  temp: (743, 6)
 word: which  temp: (425, 6)
 word: have  temp: (422, 6)
 word: would  temp: (260, 6)
 word:   temp: (0, 6)
 word:   temp: (0, 6)

"""
    CREATE A PAGES FROM ABOVE CROPS
"""

    """
    1. randoly select number of words n 
    2. select n words from set of available words
    3.select crop randomly from available crops
    4. paste crop in sentence randomly decide spacing
    
    """

In [34]:
words=["the","of","and","that","have","which","would"]

In [50]:
from random import randint

randint(0,len(words))

3

In [194]:
allPaths="./data/toyData/"
words=os.listdir(allPaths)

cropsPaths="/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//"
words

['have', 'which', 'to', 'was', 'with', 'of', 'would', 'the', 'and', 'that']

In [160]:
wordsPath=[]

for ww in words:
    temp=[]
    temp=os.listdir(allPaths+ww)
    #print(len(temp))
    wordsPath.append(temp)

3

In [298]:
df1 = pd.DataFrame(zip(list('bcdfg'), list('aeiou')), columns=['consonants', 'vowels'])
df2 = pd.DataFrame(range(5), columns=['numbers'])

In [299]:
pd.concat([df1, df2], axis=1)

  consonants vowels  numbers
0          b      a        0
1          c      e        1
2          d      i        2
3          f      o        3
4          g      u        4

"""
below part creates a crop of data and corresponding dataframe containing BB, text, 
"""

In [301]:

import time
import sys 

df1=pd.DataFrame(columns=["image_name","class","width","height","org_x1","org_y1","org_x2","org_y2","text","x","y","w","h"])

for indx in range(100):

    totWords=randint(0,len(words))
    
    orgWidth,orgHeight=1200,200
    blank_image = 255*np.ones((200,1200,3), np.uint8)
    nm=str(np.random.randint(1000))
    x1,y1=10,30
    dTemp={}
    
    for i in range(totWords):

        #print("")
        wordIndx=randint(0,len(words)-1)
        tempPaths=wordsPath[wordIndx]

        randCrops=randint(0,len(tempPaths)-1)
        randCropPath=tempPaths[randCrops]
        #print(" randCropPath=",randCropPath)
        
        textWord=words[wordIndx]
        img=cv2.imread(allPaths+textWord+"//"+randCropPath)
        #print(" img:",img.shape)
        
        try:
            h,w,c=img.shape

            #print(" h:",h," w:",w," x1:",x1,y1,x2,y2)

            blank_image[y1:y1+h,x1:x1+w] = img

            #w=words[wordIndx]
            #print(" i:",i," wordIndx:",wordIndx," word:",w," totWords:",totWords)


            if x1>1000:
                break
                
            xYolo,yYolo=(x1+x2)/2,(y1+y2)/2
            

            dTemp=pd.DataFrame({"image_name":[nm+".png"],"class":[1],
                   "width":[orgWidth],"height":[orgHeight],"org_x1":[x1],"org_y1":[y1],"org_x2":[x2],"org_y2":[y2],
                   "text":[textWord],"x":[xYolo],"y":[yYolo],"w":[1.0*w/orgWidth],"h":[1.0*h/orgHeight]})
            
            
            cv2.imwrite(cropsPaths+nm+".png",blank_image)

            x1,y1=x1+w+50,y1

            df1=pd.concat([df1,dTemp],ignore_index=True, axis = 0)
        except Exception as e:
            
            exc_type, exc_obj, exc_tb = sys.exc_info()
            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
            #print(" line number:", exc_tb.tb_lineno," e:",e)
            #print("&")
            pass

    #time.sleep(1)
    #input(" check!!")

In [302]:
df1.to_csv("/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops.csv")

In [310]:
df1.head(5)

,image_name,class,width,height,org_x1,org_y1,org_x2,org_y2,text,x,y,w,h
0,786.png,1,1200,200,10,30,1867,817,was,938.5,423.5,0.161667,0.36
1,146.png,1,1200,200,10,30,1867,817,was,938.5,423.5,0.148333,0.315
2,146.png,1,1200,200,238,30,1867,817,that,1052.5,423.5,0.135833,0.61
3,146.png,1,1200,200,451,30,1867,817,with,1159.0,423.5,0.144167,0.53
4,146.png,1,1200,200,674,30,1867,817,to,1270.5,423.5,0.081667,0.505

In [314]:
df1["phos"]=0
df1["phos"]=df1["phos"].astype(object)

df1["phoc"]=0
df1["phoc"]=df1["phoc"].astype(object)

In [315]:
import re

len(list(set(df1['text'])))
word=list(set(df1['text']))


regex = re.compile('[^a-zA-Z]')
#First parameter is the replacement, second parameter is your input string

tempPhos=[0]*165
tempPhoc=[0.0]*604
#output['Sold Count'] = output['Sold Count'].astype(object)
df1["phos"]=df1["phos"].astype(object)

for indx,row in df1.iterrows():
    
    if indx%1000==0:
        print(" indx:",indx)
        df1.to_csv("/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCropsPhosc.csv")    
    try:
        #print("\n\t w1:",w)
        w=row["text"]
        w=regex.sub('', w)
        #print("\n\t w2:",w)
        if len(w):
            phos_label = gen_label([w])
            phoc_label = gen_phoc_label([w])

            #print("\n\t train_word_phos_label=",train_word_phos_label)
            #print("\n\t keys:",len(phos_label[w]))
            #print("\n\t type:",type(phos_label[w]))
            #print("\n\t phos_label[w]=",phos_label[w])
            #df.loc[indx,"phoc"]=str(phos_label[w]) gen_phoc_label
            
            #print("\n\t phos_label =",len(phos_label[w].tolist()))
            #print("\n\t phoc_label =",len(phoc_label[w]))

            df1.at[indx,"phoc"]=phoc_label[w]
            df1.at[indx,"phos"]=phos_label[w]#.tolist()

        else:
            df1.at[indx,"phoc"]=tempPhoc
            df1.at[indx,"phos"]=tempPhos

        #input("check!!")
        
        
    except Exception as e:
        print("\n\t w:",w,"\t indx:",indx,"\t e:",e)
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        print("\n\t line number:", exc_tb.tb_lineno)
        input("check!!!")
df1.to_csv("/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCropsPhosc.csv")    


#train_word_phos_label = gen_label(list(set(df['text'])))
#train_word_phos_label = gen_label(word[5])

 indx: 0

In [318]:
df1.head(5)

,image_name,class,width,height,org_x1,org_y1,org_x2,org_y2,text,x,y,w,h,phos,phoc
0,786.png,1,1200,200,10,30,1867,817,was,938.5,423.5,0.161667,0.36,"[0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,146.png,1,1200,200,10,30,1867,817,was,938.5,423.5,0.148333,0.315,"[0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,146.png,1,1200,200,238,30,1867,817,that,1052.5,423.5,0.135833,0.61,"[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 4.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,146.png,1,1200,200,451,30,1867,817,with,1159.0,423.5,0.144167,0.53,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 1.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,146.png,1,1200,200,674,30,1867,817,to,1270.5,423.5,0.081667,0.505,"[0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [316]:

import pandas as pd
df=pd.read_csv("/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCropsPhosc.csv")

unqImages=set(df.image_name)
print("\n\t unique:",len(unqImages))
#print(data.columns)

	 unique: 91

"""
    below part convert data into yolo consumable format
"""

In [317]:
#for file in ['train','test']:
import numpy as np
import os

savePath="/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyData//"
images_path = "/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//"
allImages=os.listdir(images_path)
images_num=len(os.listdir(images_path))

labels_txt = savePath+"/"+"mnist_train1.txt"
labels_txt2 = savePath+"/"+"mnist_test1.txt"

lastName=""
curLine=""
prevLine=""
unqImg=[]
exceptionCount=0

for indx,info in df.iterrows():
    try:
        if indx%10==0:
            print("\n\t unq images:",len(unqImg))

        if len(unqImg)<90:

            with open(labels_txt, "a") as wf:
                image_path =images_path+info["image_name"]

                if indx%100==0:
                    print("\n\t path:",image_path)

                if info["image_name"]!=lastName and info["image_name"] not in unqImg:
                    curLine=image_path

                    if len(prevLine):
                        #print("\n\t prevLine:",prevLine)
                        #wf.write( image_path+ "\n")
                        wf.write(prevLine+"\n")

                else:
                    xmin,ymin=str(int(info["org_x1"])),str(int(info["org_y1"]))
                    xmax,ymax=str(int(info["org_x2"])),str(int(info["org_y2"]))
                    curLine += ' ' + ','.join([xmin, ymin, xmax, ymax, str(0)])
                    prevLine=curLine

                lastName=info["image_name"]

        elif 90<len(unqImg)<100:

            with open(labels_txt2, "a") as wf:
                image_path =images_path+info["image_name"]

                if indx%100==0:
                    print("\n\t path:",image_path)

                if info["image_name"]!=lastName:
                    curLine=image_path

                    if len(prevLine):
                        #print("\n\t prevLine:",prevLine)
                        #wf.write( image_path+ "\n")
                        wf.write(prevLine+"\n")

                else:
                    xmin,ymin=str(int(info["org_x1"])),str(int(info["org_y1"]))
                    xmax,ymax=str(int(info["org_x2"])),str(int(info["org_y2"]))
                    curLine += ' ' + ','.join([xmin, ymin, xmax, ymax, str(0)])
                    prevLine=curLine

                lastName=info["image_name"]
        elif 600<len(unqImg):
            break
            
        if info["image_name"] not in unqImg:
            unqImg.append(info["image_name"])

    except Exception as e:
        exceptionCount+=1
        print("\n\t exception index:",indx,"\t count:",exceptionCount)

print(" total exceptions:",exceptionCount)

	 unq images: 0

	 path: /home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//786.png

	 unq images: 3

	 unq images: 6

	 unq images: 8

	 unq images: 11

	 unq images: 13

	 unq images: 16

	 unq images: 19

	 unq images: 22

	 unq images: 24

	 unq images: 27

	 path: /home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//429.png

	 unq images: 30

	 unq images: 32

	 unq images: 34

	 unq images: 37

	 unq images: 39

	 unq images: 42

	 unq images: 44

	 unq images: 47

	 unq images: 49

	 unq images: 52

	 path: /home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//741.png

	 unq images: 55

	 unq images: 57

	 unq images: 59

	 unq images: 61

	 unq images: 64

	 unq images: 65

	 unq images: 67

	 unq images: 69

	 unq images: 74

	 unq images: 76

	 path: /home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/toyCrops//276.png

	 unq images: 78

	 unq images: 81

	 unq images: 82

	 unq images: 84

	 unq images: 88

	 unq images: 90
 total exceptions: 0

"""
    this part maps BB coordinate to words
"""

In [ ]:
/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/IAM_Data/IAM_test/m01-049-00-02.png

"""
    extract image name from image crops
    Test data used for PHOSCNET is used to get test image names,
    Then test images of PHOSCNET is used to get prediction from yolo model
"""

In [329]:
phoscTestData="/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/data/IAM_Data/IAM_test//"
yoloTrainData="/home/aniketag/Documents/phd/yolov5/data/datasets/forms//"

In [335]:
phoscTestCrops=os.listdir(phoscTestData)
yoloTrainImages=list(set(os.listdir(yoloTrainData)))

#set([len(nm) for nm in phoscTestCrops])

"""
import re
str = "aaaaaa|bbbbbb|ccccc|dddd"
indexes = [x.start() for x in re.finditer('\|', str)]
print(indexes) # <-- [6, 13, 19]
"""

'\nimport re\nstr = "aaaaaa|bbbbbb|ccccc|dddd"\nindexes = [x.start() for x in re.finditer(\'\\|\', str)]\nprint(indexes) # <-- [6, 13, 19]\n'

In [347]:
import cv2

matchImages=[]
unqImgnames=[]

for indx,cropName in enumerate(phoscTestCrops):
    
    cropName=list(cropName)
    cropName1=cropName[:7]
    cropName1="".join(cropName1)
    
    cropName1=cropName1+".png"
    
    if indx%1000==0:
        print(" indx:",indx)
    
    if cropName1 in yoloTrainImages:
                
        img=cv2.imread(yoloTrainData+cropName1)
        #print("cropName=",cropName," ",img.shape)
        #input(" check!!!")
        
    elif len(cropName)==18:
        
        cropName=list(cropName)
        cropName1=cropName[:8]
        cropName1="".join(cropName1)
        cropName1=cropName1+".png"
        img=cv2.imread(yoloTrainData+cropName1)
        
    else:
        
        print("cropName=",cropName)
        #input(" check!!!")
        
    unqImgnames.append(cropName1)

cropName1=list(set(cropName1))

 indx: 0
 indx: 1000
 indx: 2000
 indx: 3000
 indx: 4000
 indx: 5000
 indx: 6000
 indx: 7000
 indx: 8000
 indx: 9000

In [353]:
#phoscTestData

"""
    copy PHOSC
"""
import shutil 
unqImgnames=list(set(unqImgnames))
phoscTestImg="/home/aniketag/Documents/phd/TensorFlow-2.x-YOLOv3/phoscTest//"

print(" length:",len(unqImgnames))

for nm in unqImgnames:
    
    shutil.copy2(yoloTrainData+nm,phoscTestImg)

 length: 232

In [350]:
unqImgnames[0]

'n04-156.png'